name: 'Setup Redis with password'
description: 'Setup Redis database'
author: 'getong'
branding:
  icon: 'database'
  color: 'red'
inputs:
  redis version:
    description: 'Version of Redis to use'
    required: false
    default: 'latest'
  host port:
    description: 'the port of host'
    required: false
    default: 6379
  container port:
    description: 'The port of container'
    required: false
    default: 6379
  redis password:
    description: 'Redis Server password'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
